---
#- :name: Ceph Storage Node
#  :class: quickstack::ceph::config
- :name: Compute (Nova Network) Large
  :class: quickstack::nova_network::compute
- :name: Compute (Neutron) Large
  :class: quickstack::neutron::compute
- :name: HA All In One Controller Large
  :class:
  - quickstack::openstack_common
  - quickstack::ntp
  - quickstack::pacemaker::common
  - quickstack::pacemaker::params
  - quickstack::pacemaker::keystone
  - quickstack::pacemaker::swift
  - quickstack::pacemaker::load_balancer
  - quickstack::pacemaker::memcached
  - quickstack::pacemaker::qpid
  - quickstack::pacemaker::rabbitmq
  - quickstack::pacemaker::glance
  - quickstack::pacemaker::nova
  - quickstack::pacemaker::heat
  - quickstack::pacemaker::cinder
  - quickstack::pacemaker::horizon
  - quickstack::pacemaker::galera
  - quickstack::pacemaker::neutron
